#spring:
#  datasource:
#    password: root
#    username: root
#    url: jdbc:mysql://120.24.35.246:3306/mymall_sms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: mymall-coupon
#mybatis-plus:
##  映射文件位置
#  mapper-locations: classpath:/mapper/**/*.xml
##  主键自增你
#  global-zwf.mymall.gateway.config:
#    db-zwf.mymall.gateway.config:
#      id-type: auto
#feign:
#  httpclient:
#    connection-timeout: 10000
#    connection-timer-repeat: 10000

