# 应用名称
server:
  port: 8085
spring:
  application:
    name: mymall-gateway
  cloud:
#    alicloud:
#      access-key: LTAI4GGyAtbk6CXkvQNpg4uD
#      secret-key: dS6C71RenRNYtnNtPAbyF1HASZJa8M
#      oss:
#        endpoint: http://oss-cn-shenzhen.aliyuncs.com
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
#        - id: baidu_router
#          uri: https://www.qq.com
#          predicates:
#            - Query=url, qq
#        - id: qq_router
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url, baidu
        - id: memeber_router
          uri: lb://mymall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_router
          uri: lb://mymall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: product_router
          uri: lb://mymall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: thrid_party_router
          uri: lb://mymall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: admin_router
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}


